### PR TITLE
perf: avoid repeatedly re-parsing frames

### PR DESCRIPTION
**Pull request by sparrowt**
Hi there! Thanks for producing such an excellent tool. This was a small optimisation I spotted while looking at `stats.py` to learn more about the Austin trace/profile file format.

This should reduce the effort on parsing frames by a factor of 4 when operating on a `--full` trace, because in that case `ms` will be a list of 4 metrics but we only need to parse the frames once because they are the same in all cases.

Also add a couple of comments in `Metric.parse` which weren't obvious to me on first reading, I hope that's ok.

### CODE REVIEW

**Comment by P403n1x87** [comment]
@sparrowt Well spotted! Thanks a lot for your contribution 🙏 . I was thinking that perhaps something like a namedtuple or a dataclass would provide for a better API to collect profiles, instead of a plain list. But that's for another time 🙂 .

**Comment by sparrowt** [comment]
True yes I think that could simplify things at some point!

I'm a bit confused by the type checking issue reported:
```
austin/stats.py:263: error: Incompatible types in assignment (expression has type "List[Frame]", variable has type "str")  [assignment]
austin/stats.py:269: error: Argument "frames" to "Sample" has incompatible type "str"; expected "List[Frame]"  [arg-type]
```
given `Frame.parse` returns a `Frame` so `frames` should indeed be `List[Frame]` - my change shouldn't have altered any of the types 🤔

**Comment by P403n1x87** [comment]
Thanks. I think some sources need to be reformatted with black. Otherwise all seems good! 🙌

**Comment by sparrowt** [comment]
Ah I missed that check (I thought github was supposed to put all the failing ones at the top of the list...!)

**Comment by P403n1x87** [comment]
@sparrowt just checking whether there's an extra commit that still needs to be pushed to resolve the lining check 🙂

**Comment by sparrowt** [comment]
Gah, sorted now. I thought I'd made the necessary changes after running black locally but I'd clearly missed one!

**Comment by P403n1x87** [comment]
Awesome 🙌  Thanks a lot for your contributions! 🙂

**Comment by sparrowt** [comment]
Pleasure! In my limited local testing this was a 30% speedup which I'll take any day

**Pull request merged**
